"""create user_preferences table correctly

Revision ID: 5f6e606a3357
Revises: adbce5822e08
Create Date: 2026-02-03 00:15:14.048154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6e606a3357'
down_revision: Union[str, Sequence[str], None] = 'adbce5822e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('desired_salary', sa.Integer(), nullable=True),
    sa.Column('desired_holiday', sa.Integer(), nullable=True),
    sa.Column('max_overtime_hours', sa.Integer(), nullable=True),
    sa.Column('remote_preference', sa.String(), nullable=False),
    sa.Column('work_style', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_preferences_age'), 'user_preferences', ['age'], unique=False)
    op.create_index(op.f('ix_user_preferences_desired_holiday'), 'user_preferences', ['desired_holiday'], unique=False)
    op.create_index(op.f('ix_user_preferences_desired_salary'), 'user_preferences', ['desired_salary'], unique=False)
    op.create_index(op.f('ix_user_preferences_max_overtime_hours'), 'user_preferences', ['max_overtime_hours'], unique=False)
    op.create_index(op.f('ix_user_preferences_remote_preference'), 'user_preferences', ['remote_preference'], unique=False)
    op.create_index(op.f('ix_user_preferences_work_style'), 'user_preferences', ['work_style'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_work_style'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_remote_preference'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_max_overtime_hours'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_desired_salary'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_desired_holiday'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_age'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
