"""add job_post_title

Revision ID: 7d899a56612d
Revises: f601d589a88c
Create Date: 2026-02-28 00:55:46.837953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d899a56612d'
down_revision: Union[str, Sequence[str], None] = 'f601d589a88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_analysis_ai', sa.Column('job_post_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_analysis_ai', 'job_post_title')
    # ### end Alembic commands ###
