"""create job_posts and job_analysis

Revision ID: f601d589a88c
Revises: 5f6e606a3357
Create Date: 2026-02-14 23:49:16.607912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f601d589a88c'
down_revision: Union[str, Sequence[str], None] = '5f6e606a3357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('job_text', sa.String(), nullable=False),
    sa.Column('analysis_status', sa.String(), nullable=True),
    sa.Column('analysis_error', sa.String(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_posts_analyzed_at'), 'job_posts', ['analyzed_at'], unique=False)
    op.create_table('job_analysis_ai',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_post_id', sa.UUID(), nullable=True),
    sa.Column('matching_score', sa.Integer(), nullable=False),
    sa.Column('matching_reason', sa.String(), nullable=False),
    sa.Column('black_risk_score', sa.Integer(), nullable=False),
    sa.Column('black_risk_reason', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_analysis_ai_created_at'), 'job_analysis_ai', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_analysis_ai_job_post_id'), 'job_analysis_ai', ['job_post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_analysis_ai_job_post_id'), table_name='job_analysis_ai')
    op.drop_index(op.f('ix_job_analysis_ai_created_at'), table_name='job_analysis_ai')
    op.drop_table('job_analysis_ai')
    op.drop_index(op.f('ix_job_posts_analyzed_at'), table_name='job_posts')
    op.drop_table('job_posts')
    # ### end Alembic commands ###
